PUBLIC_SLOT1_PHONE_NUMBER = '18621614361'
PRIVATE_MMS_CASE1_ENABLE_SLOT1 = True
PRIVATE_PHONE_CASE1_ENABLE_SLOT1 = False
PRIVATE_PHONE_NAME = 'chuan'
PRIVATE_SETTINGS_ENABLE_WIFI_HYDRA = False
PRIVATE_SETTINGS_OPEN_GPS = False
